"""Explicit tol-only integral-to-DF adapter; never obtains molecular inputs.

Future input generation requires its own authorization/budget. This adapter
does not call the molecule builder or the molecule-specific rank resolver.
"""
from __future__ import annotations

import hashlib
import math

import numpy as np


def _array_record(array):
    value = np.ascontiguousarray(array, dtype=np.complex128)
    return {"shape": list(value.shape), "dtype": value.dtype.str,
            "sha256": hashlib.sha256(value.tobytes()).hexdigest()}


def tol_only_df_from_integrals(*, constant, one_body, two_body, df_tol=1e-8,
                               hermitization_tolerance=1e-10, decomposer=None):
    """Exact kwargs and all pre/post Hermitization changes are recorded.

    Tests inject a decomposer: no molecular integrals or DF decomposition are
    generated by preparation. Returned truncation value is a separate layer,
    not a complete roundoff bound or finite-time accuracy certificate.
    """
    for value in (constant, df_tol, hermitization_tolerance):
        if isinstance(value, bool) or not math.isfinite(float(value)):
            raise ValueError("FINITE_INPUT_POLICY")
    if df_tol <= 0 or hermitization_tolerance < 0:
        raise ValueError("INPUT_POLICY_RANGE")
    one = np.asarray(one_body, dtype=np.complex128)
    two = np.asarray(two_body, dtype=np.complex128)
    if one.ndim != 2 or one.shape[0] != one.shape[1] or not one.size:
        raise ValueError("ONE_BODY_SHAPE")
    n = one.shape[0]
    if two.shape != (n, n, n, n) or not np.isfinite(one).all() or not np.isfinite(two).all():
        raise ValueError("INTEGRAL_SHAPE_OR_NONFINITE")
    input_records = {"one_body": _array_record(one), "two_body": _array_record(two)}
    if decomposer is None:
        from openfermion import low_rank_two_body_decomposition
        decomposer = low_rank_two_body_decomposition
    kwargs = {"truncation_threshold": float(df_tol)}
    weights, blocks, correction, truncation = decomposer(two.copy(), **kwargs)
    weights, blocks = np.asarray(weights), np.asarray(blocks, dtype=np.complex128)
    correction = np.asarray(correction, dtype=np.complex128)
    if (weights.ndim != 1 or blocks.shape != (len(weights), n, n)
            or correction.shape != one.shape or not np.isfinite(weights).all()
            or np.any(np.imag(weights) != 0) or not np.isfinite(blocks).all()
            or not np.isfinite(correction).all()):
        raise ValueError("DECOMPOSITION_LAYOUT")
    if not math.isfinite(float(truncation)) or float(truncation) < 0:
        raise ValueError("TRUNCATION_RECORD")
    changes = []
    def hermitize(value, label):
        post = (value + value.conj().T) / 2
        difference = float(np.linalg.norm(post - value))
        if difference > hermitization_tolerance:
            raise ValueError("HERMITIZATION_POLICY:" + label)
        changes.append({"label": label, "difference_frobenius": difference,
                        "before": _array_record(value), "after": _array_record(post)})
        return post
    corrected = hermitize(one + correction, "corrected_one_body")
    fragments = tuple(hermitize(g, "fragment_" + str(i)) for i, g in enumerate(blocks))
    metadata = {"input_policy": "TOL_ONLY_NO_CONFIG_FALLBACK", "df_tol_requested": float(df_tol),
                "decomposition_kwargs": kwargs, "final_rank_supplied": False,
                "df_rank_actual": len(weights), "df_truncation_value": float(truncation),
                "input_tensors": input_records, "one_body_correction": _array_record(correction),
                "hermitization": changes, "coefficient_order": "decomposer_generation_order",
                "subsequent_coefficient_cutoff": 0.0, "representation_error_certified": False}
    from trotterlib.df_hamiltonian import DFHamiltonian
    return DFHamiltonian(float(constant), corrected, np.real(weights).astype(float), fragments, metadata)
